version: '3.8'

services:
  flask-app:
    image: flask-sensor-app:latest
    build:
      context: .
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_ENV=production

networks:
  app-network:
    driver: overlay
