{
 "title": "Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests - manager",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, status) (\n  rate(flask_http_request_total{instance=\"mystack_manager:5000\"}[1m])\n)",
     "legendFormat": "{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Requests - worker1",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, status) (\n  rate(flask_http_request_total{instance=\"mystack_worker1:6000\"}[1m])\n)",
     "legendFormat": "{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Requests - worker2",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, status) (\n  rate(flask_http_request_total{instance=\"mystack_worker2:6000\"}[1m])\n)",
     "legendFormat": "{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Requests - worker3",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, status) (\n  rate(flask_http_request_total{instance=\"mystack_worker3:6000\"}[1m])\n)",
     "legendFormat": "{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "CPU Usage (%) - manager",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"mystack_manager.*\"}[1m]) * 100",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage (%) - worker 1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"mystack_worker1.*\"}[1m]) * 100",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage (%) - worker 2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"mystack_worker2.*\"}[1m]) * 100",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage (%) - worker 3",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"mystack_worker3.*\"}[1m]) * 100",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "MemUsage (MB)-manager",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (\n  container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"mystack_manager.*\"}\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MemUsage (MB)-worker 1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (\n  container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"mystack_worker1.*\"}\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MemUsage (MB)-worker 2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (\n  container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"mystack_worker2.*\"}\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MemUsage (MB)-worker 3",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (\n  container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"mystack_worker3.*\"}\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}