Vagrant.configure("2") do |config|
  nodes = [
    { name: "node1", ip: "192.168.56.11" },  # Manager
    { name: "node2", ip: "192.168.56.12" },
    { name: "node3", ip: "192.168.56.13" },
    { name: "node4", ip: "192.168.56.14" }
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |n|
      n.vm.box = "gusztavvargadr/ubuntu-server"
      n.vm.hostname = node[:name]
      n.vm.network "private_network", ip: node[:ip]
      n.vm.network "forwarded_port", guest: 5000, host: 5000 if node[:name] == "node1"

      n.vm.provider "vmware_desktop" do |v|
        v.gui = false
        v.memory = 1024
        v.cpus = 1
      end

      n.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y docker.io python3-pip
        pip3 install flask
        systemctl start docker
        systemctl enable docker
        usermod -aG docker vagrant
      SHELL
    end
  end
end
